---
syncthing_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"

syncthing_env_default:
  TZ: "{{ syncthing_docker_settings.tz }}"
  PUID: "{{ syncthing_docker_settings.puid }}"
  PGID: "{{ syncthing_docker_settings.pgid }}"
